# -*- mode: ruby -*-
# vi: set ft=ruby :

# Lab environment for RHCSA on RHEL 10
Vagrant.configure("2") do |config|
  # vagrant-registration plugin settings
  config.registration.username = ENV['RHS_USERNAME']
  config.registration.password = ENV['RHS_PASSWORD']
  config.ssh.key_type = "ecdsa256"
  config.registration.unregister_on_halt = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"  # 2GB RAM
    vb.cpus = 2         # 2 CPU cores
  end

  # NOTE: generic/rhel10 box may not yet be available on Vagrant Cloud.
  # Check https://app.vagrantup.com/generic/boxes/rhel10 for availability.
  # As an alternative, you can build a local box from the RHEL 10 ISO.

  config.vm.define "rhel10a" do |vm|
    vm.vm.box = "generic/rhel10"
    vm.vm.hostname = "rhel10a"
    vm.vm.network "private_network", ip: "192.168.56.10"
    vm.vm.disk :disk, name: "sdb", size: "300MB"
    vm.vm.disk :disk, name: "sdc", size: "300MB"
  end

  config.vm.define "rhel10b" do |vm|
    vm.vm.box = "generic/rhel10"
    vm.vm.hostname = "rhel10b"
    vm.vm.network "private_network", ip: "192.168.56.11"
    vm.vm.disk :disk, name: "sdb", size: "300MB"
    vm.vm.disk :disk, name: "sdc", size: "300MB"
  end
end
